on:
  [ push, pull_request ]

concurrency:
    cancel-in-progress: true
    group: test-${{ github.ref }}


jobs:
    test:
        strategy:
            matrix:
                # Testing on different platforms since work with FS is platform-depended
                os: [ windows-latest, ubuntu-latest, macos-latest ]
                node: [ 14,16,18,19 ]

        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node }}
                    cache: npm
            -   run: npm ci
            -   run: npm run build
            -   run: npm run test -- --reporter=spec
